// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListWebApp.Data;

#nullable disable

namespace ToDoListWebApp.Migrations
{
    [DbContext(typeof(TeendokDbContext))]
    [Migration("20260924085816_InitialDbCreate")]
    partial class InitialDbCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ToDoListWebApp.Models.Teendo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Hatarido")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Kesz")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teendok");
                });
#pragma warning restore 612, 618
        }
    }
}
